//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 
namespace GestionListasRestrictivas {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/sdnList.xsd", IsNullable=false)]
    public partial class sdnList {
        
        private sdnListPublshInformation publshInformationField;
        
        private sdnListSdnEntry[] sdnEntryField;
        
        /// <remarks/>
        public sdnListPublshInformation publshInformation {
            get {
                return this.publshInformationField;
            }
            set {
                this.publshInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sdnEntry")]
        public sdnListSdnEntry[] sdnEntry {
            get {
                return this.sdnEntryField;
            }
            set {
                this.sdnEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListPublshInformation {
        
        private string publish_DateField;
        
        private ushort record_CountField;
        
        /// <remarks/>
        public string Publish_Date {
            get {
                return this.publish_DateField;
            }
            set {
                this.publish_DateField = value;
            }
        }
        
        /// <remarks/>
        public ushort Record_Count {
            get {
                return this.record_CountField;
            }
            set {
                this.record_CountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntry {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addressList", typeof(sdnListSdnEntryAddressList))]
        [System.Xml.Serialization.XmlElementAttribute("akaList", typeof(sdnListSdnEntryAkaList))]
        [System.Xml.Serialization.XmlElementAttribute("citizenshipList", typeof(sdnListSdnEntryCitizenshipList))]
        [System.Xml.Serialization.XmlElementAttribute("dateOfBirthList", typeof(sdnListSdnEntryDateOfBirthList))]
        [System.Xml.Serialization.XmlElementAttribute("firstName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("idList", typeof(sdnListSdnEntryIdList))]
        [System.Xml.Serialization.XmlElementAttribute("lastName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("nationalityList", typeof(sdnListSdnEntryNationalityList))]
        [System.Xml.Serialization.XmlElementAttribute("placeOfBirthList", typeof(sdnListSdnEntryPlaceOfBirthList))]
        [System.Xml.Serialization.XmlElementAttribute("programList", typeof(sdnListSdnEntryProgramList))]
        [System.Xml.Serialization.XmlElementAttribute("remarks", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("sdnType", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("title", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("uid", typeof(ushort))]
        [System.Xml.Serialization.XmlElementAttribute("vesselInfo", typeof(sdnListSdnEntryVesselInfo))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryAddressList {
        
        private sdnListSdnEntryAddressListAddress[] addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public sdnListSdnEntryAddressListAddress[] address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryAddressListAddress {
        
        private ushort uidField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string postalCodeField;
        
        private string countryField;
        
        /// <remarks/>
        public ushort uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string stateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryAkaList {
        
        private sdnListSdnEntryAkaListAka[] akaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aka")]
        public sdnListSdnEntryAkaListAka[] aka {
            get {
                return this.akaField;
            }
            set {
                this.akaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryAkaListAka {
        
        private ushort uidField;
        
        private string typeField;
        
        private string categoryField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        /// <remarks/>
        public ushort uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryCitizenshipList {
        
        private sdnListSdnEntryCitizenshipListCitizenship[] citizenshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citizenship")]
        public sdnListSdnEntryCitizenshipListCitizenship[] citizenship {
            get {
                return this.citizenshipField;
            }
            set {
                this.citizenshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryCitizenshipListCitizenship {
        
        private ushort uidField;
        
        private string countryField;
        
        private bool mainEntryField;
        
        /// <remarks/>
        public ushort uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public bool mainEntry {
            get {
                return this.mainEntryField;
            }
            set {
                this.mainEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryDateOfBirthList {
        
        private sdnListSdnEntryDateOfBirthListDateOfBirthItem[] dateOfBirthItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dateOfBirthItem")]
        public sdnListSdnEntryDateOfBirthListDateOfBirthItem[] dateOfBirthItem {
            get {
                return this.dateOfBirthItemField;
            }
            set {
                this.dateOfBirthItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryDateOfBirthListDateOfBirthItem {
        
        private ushort uidField;
        
        private string dateOfBirthField;
        
        private bool mainEntryField;
        
        /// <remarks/>
        public ushort uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public bool mainEntry {
            get {
                return this.mainEntryField;
            }
            set {
                this.mainEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryIdList {
        
        private sdnListSdnEntryIdListID[] idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public sdnListSdnEntryIdListID[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryIdListID {
        
        private uint uidField;
        
        private string idTypeField;
        
        private string idNumberField;
        
        private string idCountryField;
        
        private string issueDateField;
        
        private string expirationDateField;
        
        /// <remarks/>
        public uint uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
            }
        }
        
        /// <remarks/>
        public string idCountry {
            get {
                return this.idCountryField;
            }
            set {
                this.idCountryField = value;
            }
        }
        
        /// <remarks/>
        public string issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryNationalityList {
        
        private sdnListSdnEntryNationalityListNationality[] nationalityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nationality")]
        public sdnListSdnEntryNationalityListNationality[] nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryNationalityListNationality {
        
        private ushort uidField;
        
        private string countryField;
        
        private bool mainEntryField;
        
        /// <remarks/>
        public ushort uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public bool mainEntry {
            get {
                return this.mainEntryField;
            }
            set {
                this.mainEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryPlaceOfBirthList {
        
        private sdnListSdnEntryPlaceOfBirthListPlaceOfBirthItem[] placeOfBirthItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("placeOfBirthItem")]
        public sdnListSdnEntryPlaceOfBirthListPlaceOfBirthItem[] placeOfBirthItem {
            get {
                return this.placeOfBirthItemField;
            }
            set {
                this.placeOfBirthItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryPlaceOfBirthListPlaceOfBirthItem {
        
        private ushort uidField;
        
        private string placeOfBirthField;
        
        private bool mainEntryField;
        
        /// <remarks/>
        public ushort uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string placeOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public bool mainEntry {
            get {
                return this.mainEntryField;
            }
            set {
                this.mainEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryProgramList {
        
        private string[] programField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("program")]
        public string[] program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/sdnList.xsd")]
    public partial class sdnListSdnEntryVesselInfo {
        
        private string callSignField;
        
        private string vesselTypeField;
        
        private string vesselFlagField;
        
        private ushort grossRegisteredTonnageField;
        
        private bool grossRegisteredTonnageFieldSpecified;
        
        private string vesselOwnerField;
        
        private ushort tonnageField;
        
        private bool tonnageFieldSpecified;
        
        /// <remarks/>
        public string callSign {
            get {
                return this.callSignField;
            }
            set {
                this.callSignField = value;
            }
        }
        
        /// <remarks/>
        public string vesselType {
            get {
                return this.vesselTypeField;
            }
            set {
                this.vesselTypeField = value;
            }
        }
        
        /// <remarks/>
        public string vesselFlag {
            get {
                return this.vesselFlagField;
            }
            set {
                this.vesselFlagField = value;
            }
        }
        
        /// <remarks/>
        public ushort grossRegisteredTonnage {
            get {
                return this.grossRegisteredTonnageField;
            }
            set {
                this.grossRegisteredTonnageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grossRegisteredTonnageSpecified {
            get {
                return this.grossRegisteredTonnageFieldSpecified;
            }
            set {
                this.grossRegisteredTonnageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string vesselOwner {
            get {
                return this.vesselOwnerField;
            }
            set {
                this.vesselOwnerField = value;
            }
        }
        
        /// <remarks/>
        public ushort tonnage {
            get {
                return this.tonnageField;
            }
            set {
                this.tonnageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tonnageSpecified {
            get {
                return this.tonnageFieldSpecified;
            }
            set {
                this.tonnageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/sdnList.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        addressList,
        
        /// <remarks/>
        akaList,
        
        /// <remarks/>
        citizenshipList,
        
        /// <remarks/>
        dateOfBirthList,
        
        /// <remarks/>
        firstName,
        
        /// <remarks/>
        idList,
        
        /// <remarks/>
        lastName,
        
        /// <remarks/>
        nationalityList,
        
        /// <remarks/>
        placeOfBirthList,
        
        /// <remarks/>
        programList,
        
        /// <remarks/>
        remarks,
        
        /// <remarks/>
        sdnType,
        
        /// <remarks/>
        title,
        
        /// <remarks/>
        uid,
        
        /// <remarks/>
        vesselInfo,
    }
}
